Djm/matrix delays
dajmcdon/rtestim pull request #61
Opened 2024-04-19 16:16 UTC by dajmcdon

2024-05-03 22:11 UTC, jiapivialiu requested changes
They all look good to me except a typo and a potential bug in delay matrix for time-varying delays. They are very helpful!

2024-05-03 22:27 UTC, dajmcdon commented on vignettes/delay-distributions.Rmd
> +delay_mat <- delay_mat / rowSums(delay_mat) # renormalize
I don't think any are 0...

2024-05-03 22:35 UTC, jiapivialiu commented on vignettes/delay-distributions.Rmd
> +delay_mat <- delay_mat / rowSums(delay_mat) # renormalize
`delay` is a nonzero vector of length 15, but `n` is more than 1000 here, so `backer_delay` is filled by 0 at the beginning, which makes more than 1000 rows all 0s.

2024-05-03 22:59 UTC, dajmcdon commented on vignettes/delay-distributions.Rmd
> +delay_mat <- delay_mat / rowSums(delay_mat) # renormalize
I see. For the future, it's helpful to explain a little more fully or suggest a change.

2024-05-03 23:00 UTC, dajmcdon commented on vignettes/delay-distributions.Rmd
> +for (iter in 2:n) delay_mat[iter, 1:iter] <- backer_delay[1:iter]
```suggestion
backer_delay <- c(0, delay, rep(0, n - length(delay) - 1))
delay_mat <- matrix(0, n, n)
delay_mat[1,1] <- 1
for (iter in 2:n) delay_mat[iter, 1:iter] <- rev(backer_delay[1:iter])
```

2024-05-04 01:27 UTC, jiapivialiu approved these changes

2024-05-04 01:27 UTC, merged